# Bank RFM Analysis

#### RFM analysis is a very effective method for segmenting by analyzing customer behavior. This analysis helps the company understand which customer more valuable, which ones are in danger of losing, and which ones need to be targeted with special campaigns. The word "RFM" is formed from the initial letters of English words denoting three main criteria:

-	Recency : How many days passed from the customer's  last operation?
-	Frequency: How many times has the customer made transactions in the last 1 month (or 3 months)? (Number of transactions).
-	Monetary: What is total turnover of the customer’s transactions? Or what is the net interest/commission income that the bank brings in?

In [4]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

### Connecting PostgreSQL

In [6]:
engine = create_engine("postgresql+psycopg2://postgres:1234@localhost:5432/bank_dwh")

In [7]:
query_trs = """ SELECT * FROM fact_transactions"""

df_trs = pd.read_sql(query_trs,engine)

df_trs.head(3)

,transaction_key,date_key,account_key,customer_key,product_key,branch_key,amount,direction,transaction_type,channel,currency,exchange_rate,amount_eur,amount_gbp,is_suspicious
0,1,782,18343,8429,6,4,19.89,D,POS,Mobile,GBP,1.18,23.47,19.89,False
1,2,627,995,457,6,7,49.66,D,POS,Mobile,GBP,1.18,58.60,49.66,False
2,3,928,6241,2892,6,1,181.04,D,POS,Branch,GBP,1.18,213.63,181.04,False

In [8]:
query_d = """ SELECT * FROM dim_date """

df_d = pd.read_sql(query_d, engine)

df_d.head()

,date_key,full_date,day_of_week,day_name,week_number,month_number,month_name,quarter,year,is_weekend,is_business_day
0,1,2024-01-01,1,Monday,1,1,January,1,2024,False,True
1,2,2024-01-02,2,Tuesday,1,1,January,1,2024,False,True
2,3,2024-01-03,3,Wednesday,1,1,January,1,2024,False,True
3,4,2024-01-04,4,Thursday,1,1,January,1,2024,False,True
4,5,2024-01-05,5,Friday,1,1,January,1,2024,False,True

### REPORT DATE - 01.01.2027

### Recency

In [11]:
# Date information is entered into the transactions table.
df_trs = pd.merge(df_trs, df_d, how="inner", on='date_key')

r = df_trs.groupby('customer_key', as_index=False)['full_date'].max()

r['report_date'] = '2027-01-01'

r['report_date'] = pd.to_datetime(r['report_date'])
r['full_date'] = pd.to_datetime(r['full_date'])

r['days'] = (r['report_date'] - r['full_date']).dt.days

r.head()

   customer_key  full_date report_date  days
0             1 2026-08-26  2027-01-01   128
1             2 2026-12-02  2027-01-01    30
2             3 2026-07-18  2027-01-01   167
3             4 2026-12-29  2027-01-01     3
4             5 2026-12-06  2027-01-01    26

### Frequency

In [13]:
f = df_trs.groupby('customer_key', as_index=False).agg(count=('customer_key','count'))

f.head()

   customer_key  count
0             1      9
1             2     18
2             3     11
3             4     15
4             5     12

### Monetary

In [15]:
m = df_trs.groupby('customer_key',as_index=False)['amount'].sum()

m.head()

   customer_key   amount
0             1   639.46
1             2  1907.12
2             3  1276.29
3             4  1062.85
4             5  1154.99

### Now we're combining the separately calculated tables

In [17]:
rfm = pd.merge(r , f , how='left', on='customer_key')

rfm = pd.merge(rfm , m , how='left', on='customer_key')

rfm = rfm.drop(columns=['full_date','report_date'])

rfm.head()

   customer_key  days  count   amount
0             1   128      9   639.46
1             2    30     18  1907.12
2             3   167     11  1276.29
3             4     3     15  1062.85
4             5    26     12  1154.99

## Prices which was got is assesment from 5 to 1 and combining.

In [19]:
rfm['R_Score'] = pd.qcut(rfm['days'], 5 , labels = [5,4,3,2,1])

rfm['F_Score'] = pd.qcut(rfm['count'], 5 , labels = [5,4,3,2,1])

rfm['M_Score'] = pd.qcut(rfm['amount'], 5 , labels = [5,4,3,2,1])

rfm['RFM'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

rfm = rfm.drop(columns=['days','count','amount'])

rfm

      customer_key R_Score F_Score M_Score  RFM
0                1       2       5       5  255
1                2       4       2       2  422
2                3       1       4       3  143
3                4       5       3       4  534
4                5       4       4       4  444
...            ...     ...     ...     ...  ...
9994          9996       3       1       1  311
9995          9997       1       5       4  154
9996          9998       2       2       4  224
9997          9999       2       3       3  233
9998         10000       1       5       5  155

[9999 rows x 5 columns]

In [20]:
# We replace the combination of R and F scores with relevant customer segmentation.
segs = {
    r'[1-2][1-2]': 'Hibernating',
    r'[1-2][3-4]': 'At Risk',
    r'[1-2]5': 'Can\'t Loose Them',
    r'3[1-2]': 'About To Sleep',
    r'33': 'Need Attention',
    r'[3-4][4-5]': 'Loyal Customers',
    r'41': 'Promising',
    r'51': 'New Customers',
    r'[4-5][2-3]': 'Potential Loyalists',
    r'5[4-5]': 'Champions'
}

# Using regex patterns, we map RF codes to segment names in the dictionary

rfm['Segment'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str)
rfm['Segment'] = rfm['Segment'].replace(segs, regex=True)

In [21]:
rfm

      customer_key R_Score F_Score M_Score  RFM              Segment
0                1       2       5       5  255     Can't Loose Them
1                2       4       2       2  422  Potential Loyalists
2                3       1       4       3  143              At Risk
3                4       5       3       4  534  Potential Loyalists
4                5       4       4       4  444      Loyal Customers
...            ...     ...     ...     ...  ...                  ...
9994          9996       3       1       1  311       About To Sleep
9995          9997       1       5       4  154     Can't Loose Them
9996          9998       2       2       4  224          Hibernating
9997          9999       2       3       3  233              At Risk
9998         10000       1       5       5  155     Can't Loose Them

[9999 rows x 6 columns]